### ISSUE TITLE
Float division by zero

### ISSUE THREAD

**Issue by tstricker** [parklab/NGSCheckMate#17]
I know this has come up twice before, but neither case appears to apply to me. I can't figure out this error. 

Generate Data Set from /data/strickt2/desmoid2/sequence/readgroup/raw.vcf/
using this bed file : /home/strickt2/SEQanalysis/NGSCheckMate/SNP/SNP_GRCh37_hg19_wChr.bed
Traceback (most recent call last):
  File "/home/strickt2/SEQanalysis/NGSCheckMate/ncm.py", line 1460, in <module>
    createDataSetFromDir(base_dir,bedFile)
  File "/home/strickt2/SEQanalysis/NGSCheckMate/ncm.py", line 220, in createDataSetFromDir
    real_depth[file] = depth[file] / float(real_count[file])
ZeroDivisionError: float division by zero

**Comment by tstricker** [comment]
HI Sejoon,

Thanks, I figured it out this weekend. The GATK files I have do not have DP4, but rather just depth. So I used samtools to generate vcfs and piped those to NGScheckmate. It worked great and was super helpful.

Cheers

TS



On Jul 29, 2018, at 9:28 PM, sejooning <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi tstricker,

The NGSCheckMate supports below VCF files.

  1.  Single-sample VCF files from samtools and GATK's.
  2.  A Multi-samples VCF file (GATK).

Otherwise, could you please share your VCF files? I would like to check the details.

Best,
Sejoon Lee
