### ISSUE TITLE
VCF files to use

### ISSUE THREAD

**Issue by plbngl** [parklab/NGSCheckMate#25]
Hello!
I want to compare the genotype of 10 different samples obtained from either snp arrays and ATAC seq to check for sample swaps.
For each of the 10 samples I have one VCF from the array and one from samtools mpileup from ATAC seq. I also have  bed file with ~50.000 variants that I selected to be in high coverage peaks and polymorphic. I tried to run your program on these 20 vfcs but I got this error:

 python $NCM_HOME/ncm.py -V -f -d sample_swap/sample_vcfs/ -O sample_swap/ -bed sample_swap/min20cov_snps.bed

Generate Data Set from sample_swap/sample_vcfs/
using this bed file : sample_swap/min20cov_snps.bed
Traceback (most recent call last):
  File "/home/pbenaglio/NGSCheckMate/ncm.py", line 1460, in <module>
    createDataSetFromDir(base_dir,bedFile)
  File "/home/pbenaglio/NGSCheckMate/ncm.py", line 220, in createDataSetFromDir
    real_depth[file] = depth[file] / float(real_count[file])
ZeroDivisionError: float division by zero

I wonder if it is possible to use vcf files from array data at all?

Thank you very much,
Best,
Paola

**Comment by shannjiang** [comment]
Hi I got the same error but from different line:
Traceback (most recent call last):
  File "/sc/arion/projects/H_PBG/scripts/NGSCheckMate/ncm.py", line 1470, in <module>
    createDataSetFromList(base_list,bedFile)
  File "/sc/arion/projects/H_PBG/scripts/NGSCheckMate/ncm.py", line 403, in createDataSetFromList
    real_depth[file] = depth[file] / float(real_count[file])
ZeroDivisionError: float division by zero

Have you resolved it finally?
