### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by kbarrr** [parklab/NGSCheckMate#50]
Traceback (most recent call last):
  File "ncm.py", line 1453, in <module>
    createDataSetFromDir(base_dir,bedFile)
  File "ncm.py", line 222, in createDataSetFromDir
    real_depth[file] = depth[file] / float(real_count[file])
ZeroDivisionError: float division by zero

HELPPPPPPPPPPPPPP

**Comment by kbarrr** [comment]
(ngscheckmate-env)

 python ncm.py -B --list M1M2.txt -bed SNP_GRCh38_hg38_wChr.bed -O M1M2_results

this is the command i run.
 
 
 PLEASE HELP ME
