### ISSUE TITLE
 File "ncm.py", line 1453, in <module>   File "ncm.py", line 222, in createDataSetFromDir  ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by kbarrr** [parklab/NGSCheckMate#51]
code: python ncm.py -B -f -l M1M2.txt -O M1M2_results -N outputfile_prefix -bed SNP_GRCh38_hg38_wChr.bed

WARNNING : NCM_HOME is not defined yet. Therefore, program will try to search ncm.conf file from the current directory
1.6
/home/seisbio/mambaforge/envs/ngscheckmate-env/bin/samtools mpileup -uf GCA_000001405.29_GRCh38.p14_genomic.fna -l SNP_GRCh38_hg38_wChr.bed M1_dedup_filtrado_sorted.bam | /home/seisbio/mambaforge/envs/ngscheckmate-env/bin/bcftools call -c > M1M2_results/M1_dedup_filtrado_sorted.vcf
[mpileup] 1 samples in 1 input files
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
<mpileup> Set max per-file depth to 8000
/home/seisbio/mambaforge/envs/ngscheckmate-env/bin/samtools mpileup -uf GCA_000001405.29_GRCh38.p14_genomic.fna -l SNP_GRCh38_hg38_wChr.bed M2_dedup_filtrado_sorted.bam | /home/seisbio/mambaforge/envs/ngscheckmate-env/bin/bcftools call -c > M1M2_results/M2_dedup_filtrado_sorted.vcf
[mpileup] 1 samples in 1 input files
Note: none of --samples-file, --ploidy or --ploidy-file given, assuming all sites are diploid
<mpileup> Set max per-file depth to 8000
Generate Data Set from M1M2_results
using this bed file : SNP_GRCh38_hg38_wChr.bed
Traceback (most recent call last):
  File "ncm.py", line 1453, in <module>
    createDataSetFromDir(base_dir,bedFile)
  File "ncm.py", line 222, in createDataSetFromDir
    real_depth[file] = depth[file] / float(real_count[file])
ZeroDivisionError: float division by zero

someone can help?

**Comment by SooLee** [comment]
Hi Karla, Is there any chance that the input bam file is empty?

**Comment by kbarrr** [comment]
Hello. No, the bam file is not empty. However i tried with fastq files and worked perfectly!!!

**Comment by shashwatsahay** [comment]
Same error here!!!!

Any solutions will be deeply appreciated

first time around it ran without hiccups though

**Comment by SooLee** [comment]
or possibly the chromosomes names don't match between the bed and the bam?
e.g with or without 'chr'

**Comment by shashwatsahay** [comment]
nope that wasn't the case interestingly if i just re-ran it it worked fine which confuses me even further

**Comment by ls233** [comment]
dear author, thanks for sharing this useful utility. 

I noticed that for some shallow BAM files, your utility generate the following error:

NGSCheckMate/ncm.py", line 220, in createDataSetFromDir
    real_depth[file] = depth[file] / float(real_count[file])
ZeroDivisionError: float division by zero


Would it be possible to validate the BAM file in the preflight so that your utility can be integrated into larger pipelines without risking to fail the larger run?
